version: '3.8'

services:
  frontend:
    container_name: mi-saas-frontend
    build:
      context: ./agendamiento-app  # Nombre de tu carpeta del proyecto
      dockerfile: Dockerfile
      # --- AQU√ç PASAMOS LAS VARIABLES AL BUILD ---
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "80:80"
    restart: always